Coding Tasks 9: Sorting

1. Sort a random array.

2. Sort rows based on the second column.

3. Find top-5 largest values using argsort.

Coding Tasks 9: Sorting (enhanced difficulty level)

1. Generate a 2D NumPy array of shape (8 x 5) with random values.

2. Sort each row independently in descending order.

3. Sort the rows based on the values in the second column.

4. Identify the index of the row with the highest total sum.

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0, 100, 10)
sorted_arr = np.sort(arr)

print(f"Task 1 \nOriginal:", arr)
print("Sorted:", sorted_arr)

Task 1 
Original: [13 71 98 18 90 90  5 84 75 55]
Sorted: [ 5 13 18 55 71 75 84 90 90 98]


In [4]:
arr = np.random.randint(0, 50, (5, 3))

sorted_rows = arr[arr[:, 1].argsort()]

print("Task 2\nOriginal array:\n", arr)
print("Sorted by second column:\n", sorted_rows)

Task 2
Original array:
 [[44 40 27]
 [10 27  6]
 [38 40 29]
 [45 19  3]
 [37 45  6]]
Sorted by second column:
 [[45 19  3]
 [10 27  6]
 [44 40 27]
 [38 40 29]
 [37 45  6]]


In [5]:
arr = np.random.randint(0, 100, 20)

top5_indices = np.argsort(arr)[-5:]
top5_values = arr[top5_indices]

print("Task 3\nArray:", arr)
print("Top 5 values:", top5_values)

Task 3
Array: [87 32 31 78 28 82 67 62 15 28 62 55 76 91 70 23 17  8 60 61]
Top 5 values: [76 78 82 87 91]


In [6]:
arr = np.random.randint(0, 100, (8, 5))
print("Task 2.1\nOriginal array:\n", arr)

Task 2.1
Original array:
 [[92 71 69 63 56]
 [57 43 12 38 99]
 [61 13 68 56 40]
 [44 81 14 45 28]
 [37 56 25 57 44]
 [57 70 27 13 48]
 [90 13 65 25 53]
 [21 99  5 15 17]]


In [7]:
sorted_rows = np.sort(arr, axis=1)[:, ::-1]

print("Task 2.2\nRows sorted descending:\n", sorted_rows)

Task 2.2
Rows sorted descending:
 [[92 71 69 63 56]
 [99 57 43 38 12]
 [68 61 56 40 13]
 [81 45 44 28 14]
 [57 56 44 37 25]
 [70 57 48 27 13]
 [90 65 53 25 13]
 [99 21 17 15  5]]


In [12]:
sorted_by_second = arr[arr[:, 1].argsort()]

print("Task 2.3\nRows sorted by second column:\n", sorted_by_second)

Task 2.3
Rows sorted by second column:
 [[61 13 68 56 40]
 [90 13 65 25 53]
 [57 43 12 38 99]
 [37 56 25 57 44]
 [57 70 27 13 48]
 [92 71 69 63 56]
 [44 81 14 45 28]
 [21 99  5 15 17]]


In [11]:
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)

print("Task 2.4\nRow sums:", row_sums)
print("Index of row with highest sum:", max_row_index)

Task 2.4
Row sums: [351 249 238 212 219 215 246 157]
Index of row with highest sum: 0
