In [1]:
import numpy as np

1. Use fancy indexing to reorder rows

In [9]:
print("Task 1.1:")
matrix = np.arange(1, 13).reshape(4, 3)
print("Original Matrix:\n", matrix)

# We want to reorder the rows from [0, 1, 2, 3] to [3, 0, 2, 1]
row_indices = [3, 0, 2, 1]
reordered_matrix = matrix[row_indices]
print("\nReordered Matrix:\n", reordered_matrix)

Task 1.1:
Original Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reordered Matrix:
 [[10 11 12]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]]


2. Extract random samples from an array.

In [ ]:
print("Task 1.2: Random Sample:")
data_array = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G'])

random_indices = np.random.randint(0, len(data_array), size=3)
random_samples = data_array[random_indices]
print(f"Random Indices: {random_indices}")
print(f"Extracted Samples: {random_samples}")

Task 1.2: Random Sample:
Random Indices: [2 2 6]
Extracted Samples: ['C' 'C' 'G']


3. Swap elements using index arrays.

In [11]:
print("Task 1.3:")
arr_to_swap = np.array([10, 20, 30, 40])
print("Original array:", arr_to_swap)

swap_indices = [3, 1, 2, 0]
swapped_array = arr_to_swap[swap_indices]
print("Swapped array: ", swapped_array)

Task 1.3:
Original array: [10 20 30 40]
Swapped array:  [40 20 30 10]


1. Create a 1D NumPy array of length 30 with random integers between O and 100.

In [ ]:
print("Task 2.1:")
arr = np.random.randint(0, 101, size=30)
print("Original Array:\n", arr)

Task 2.1:
Original Array:
 [ 90  58  41  91  59  79  14  61  61  46  61  50  54  63   2 100  50   6
  20  72  38  17   3  88  59  13   8  89  52   1]


2. Using fancy indexing, select elements located at prime-number indices.

In [26]:
prime_numbers = []
def is_prime(n):
    limit = int(n**0.5) + 1
    
    for i in range(2, limit):
        if n % i == 0:
            return False
    return True

for i in range(2, 31):
    if is_prime(i)==True:
        prime_numbers.append(i)
    else:
        pass
print(prime_numbers)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [27]:
print("Task 2.2:")
prime_indices = np.array(prime_numbers)

prime_elements = arr[prime_indices]
print("Indices used:\n", prime_indices)
print("Elements at prime indices:\n", prime_elements)

Task 2.2:
Indices used:
 [ 2  3  5  7 11 13 17 19 23 29]
Elements at prime indices:
 [41 -1 79 61 50 63  6 72 88  1]


3. Replace values at indices divisible by 3 with -1.

In [24]:
print("Task 2.3:")
div_by_3_indices = np.arange(0, 30, 3) 

print(f"\n{div_by_3_indices}")
arr[div_by_3_indices] = -1
print("Array after replacement:\n", arr)

Task 2.3:

[ 0  3  6  9 12 15 18 21 24 27]
Array after replacement:
 [-1 58 41 -1 59 79 -1 61 61 -1 61 50 -1 63  2 -1 50  6 -1 72 38 -1  3 88
 -1 13  8 -1 52  1]


4. Verify the changes using NumPy boolean expressions (do not use loops)

In [28]:
print("Task 2.4:")

all_indices = np.arange(30)

mask = (all_indices % 3 == 0)

all_replaced_correctly = np.all(arr[mask] == -1)
no_unintended_changes = np.all(arr[~mask] != -1) 

print("Were all target indices set to -1? :", all_replaced_correctly)
if all_replaced_correctly:
    print("Verification successful!")

print(f"\n{all_indices}")
print(f"\n{mask}")
print(f"\n{no_unintended_changes}")

Task 2.4:
Were all target indices set to -1? : True
Verification successful!

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False]

True
